# Generated by Django 5.2.4 on 2025-07-14 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_playerseasonstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
